workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 60
    environment:
      node: latest   # Node.js нужен для npm
      flutter: none  # Flutter не нужен
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build APK
        script: cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
